[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bathycube"
dynamic = ["version"]
description = "A Python implementation of the UNH CUBE module for gridding Bathymetric data."
readme = "README.md"
requires-python = ">=3.8.2"
license = {text = "MIT"}
authors = [
    {name = "Eric Younkin", email = "eric.g.younkin@noaa.gov"},
]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "numba>=0.52.0",
    "numpy>=1.20.1",
]

[project.urls]
Homepage = "https://github.com/noaa-ocs-hydrography/bathycube"

[tool.setuptools.dynamic]
version = {attr = "bathycube.__version__.__version__"}

[tool.setuptools.packages.find]
exclude = ["tests*"]
